require("dotenv").config();
const http = require("http");
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const morgan = require("morgan");
const { Server } = require("socket.io");
const authRoutes = require("./src/routes/auth.routes");
const tripRoutes = require("./src/routes/trips.routes");
const matchingRoutes = require("./src/routes/matching.routes");
const paymentRoutes = require("./src/routes/payments.routes");
const { initSockets } = require("./src/sockets/socket.service");
const { errorHandler, notFoundHandler } = require("./src/middleware/error");
const app = express();
const server = http.createServer(app);
const allowedOrigins = (process.env.CORS_ORIGIN || "").split(",").map(o => o.trim()).filter(Boolean);
app.use(helmet());
app.use(cors({ origin(origin, cb) { if (!origin || allowedOrigins.length === 0 || allowedOrigins.includes(origin)) return cb(null, true); return cb(new Error("Not allowed by CORS")); }, credentials: true }));
app.use("/api/payments/webhook", express.raw({ type: "application/json" }));
app.use(express.json({ limit: "1mb" }));
app.use(morgan(process.env.NODE_ENV === "production" ? "combined" : "dev"));
app.get("/", (_req, res) => res.json({ app: "RideAlong API", status: "online", version: "1.0.0" }));
app.get("/health", (_req, res) => res.json({ ok: true, timestamp: new Date().toISOString() }));
app.use("/api/auth", authRoutes);
app.use("/api/trips", tripRoutes);
app.use("/api/matching", matchingRoutes);
app.use("/api/payments", paymentRoutes);
app.use(notFoundHandler);
app.use(errorHandler);
const io = new Server(server, { cors: { origin: allowedOrigins.length ? allowedOrigins : "*", methods: ["GET", "POST"], credentials: true } });
initSockets(io);
const PORT = process.env.PORT || 3000;
server.listen(PORT, () => console.log(`RideAlong backend running on port ${PORT}`));
